apiVersion: v1
kind: Namespace
metadata:
  name: mindwell-staging
  labels:
    name: mindwell-staging
    environment: staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: mindwell-production
  labels:
    name: mindwell-production
    environment: production